services:
  App\Application\Http\Handler\HomePage:
  App\Application\EventListener\SomeEventListener:
    tags:
      - { name: 'event_listener', event: 'App\Application\Event\SomeEvent' }

  some.command:
    class: App\Application\Command\SomeCommandExample
    tags:
      - { name: 'console.command', command: 'my:custom:command' }

parameters:
  debug: false
  config_cache_enabled: true
  monolog:
    handlers:
      default:
        type: 'stream'
        options:
          stream: 'var/log/%date%-default.log'
          level: 400
