services:
  App\Application\EventListener\SomeEventListener:
  App\Application\Http\Handler\HomePage:
  Psr\Log\LoggerInterface:
    factory: [Antidot\Logger\Container\MonologFactory]

parameters:
  debug: false
  config_cache_enabled: true
  app-events:
    event-listeners:
      App\Application\Event\SomeEvent:
        - 'App\Application\EventListener\SomeEventListener'
  monolog:
    handlers:
      default:
        type: 'stream'
        options:
          stream: 'var/log/%date%-default.log'
          level: 400
